In [1]:
# manual normalization

def norm_manual(data):
    n_max = max(data)
    n_min = min(data)
    l_data = len(data) #panjang data

    for i in range(0,l_data):
        data[i] = (data[i] - n_min) / (n_max - n_min)

    return data

In [2]:
nilai = [10,13,14,12]
nilai_norm = norm_manual(nilai)
nilai_norm

[0.0, 0.75, 1.0, 0.5]

In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [4]:
data = [[100, 0.001],
[8, 0.05],
[50, 0.005],
[88, 0.07],
[4, 0.1]]
data = np.asarray(data)
data.shape

scaler = MinMaxScaler()

scaled = scaler.fit_transform(data)
scaled

array([[1.        , 0.        ],
       [0.04166667, 0.49494949],
       [0.47916667, 0.04040404],
       [0.875     , 0.6969697 ],
       [0.        , 1.        ]])

In [5]:
def stand_manual(data):
    n_mean = np.mean(data)
    n_std = np.std(data)
    l_data = len(data)

    for i in range(0,l_data):
        data[i] = (data[i] - n_mean) / n_std

    return data

In [6]:
nilai = [10,11,12,13,14,18,20]
nilai_std = stand_manual(nilai)
nilai_std

[-1.1686974195815552,
 -0.8765230646861664,
 -0.5843487097907776,
 -0.2921743548953888,
 0.0,
 1.1686974195815552,
 1.7530461293723327]

In [7]:
data = [[100, 0.001],
[8, 0.05],
[50, 0.005],
[88, 0.07],
[4, 0.1]]
print ("data asli : ")
print(data)

scaler = StandardScaler()

print ("data transform hasil standarisasi : ")

scaled = scaler.fit_transform(data)
scaled

data asli : 
[[100, 0.001], [8, 0.05], [50, 0.005], [88, 0.07], [4, 0.1]]
data transform hasil standarisasi : 


array([[ 1.26398112, -1.16389967],
       [-1.06174414,  0.12639634],
       [ 0.        , -1.05856939],
       [ 0.96062565,  0.65304778],
       [-1.16286263,  1.44302493]])

In [8]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_econder = OrdinalEncoder()

oe = [
      ['State Polytechnics of Malang'],
      ['Electronic State Polytechnics of Surabaya'],
      ['State Polytechnics of Jakarta'],
      ['State Polytechnics of Padang'],
      ['State Polytechnics of Badung']]

print(ordinal_econder.fit_transform(oe))

[[3.]
 [0.]
 [2.]
 [4.]
 [1.]]


In [9]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer()

dt = [
        {'name' : 'POLINEMA'},
        {'name' : 'PENS'},
        {'name' : 'PNJ'},
        {'name' : 'POLBAN'},
        {'name' : 'POLIJE'}
]

poly_dv = dv.fit_transform(dt)
poly_dv.toarray()

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [10]:
from sklearn.preprocessing import OneHotEncoder
dummy_encoding = OneHotEncoder(drop = 'first')

de = [
    ['State Polytechnics of Malang'],
      ['Electronic State Polytechnics of Surabaya'],
      ['State Polytechnics of Jakarta']
]

print(dummy_encoding.fit_transform(de).toarray())

[[0. 1.]
 [0. 0.]
 [1. 0.]]


In [13]:
#corpus / text
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
print(response)

  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811


In [15]:
vectorizer.get_feature_names()

['ate',
 'away',
 'cat',
 'end',
 'finally',
 'house',
 'little',
 'mouse',
 'ran',
 'saw',
 'story',
 'tiny']

In [18]:
f=open("orange.txt","r")
data = f.read()
print(data)
f.close()

                The Five Orange Pips

  When I glance over my notes and records of the Sherlock
Holmes cases between the years '82 and '90, I am faced by so
many which present strange and interesting features that it is no
easy matter to know which to choose and which to leave. Some,
however, have already gained publicity through the papers, and
others have not offered a field for those peculiar qualities which
my friend possessed in so high a degree, and which it is the
object of these papers to illustrate. Some, too, have baffled his
analytical skill, and would be, as narratives, beginnings without
an ending, while others have been but partially cleared up, and
have their explanations founded rather upon conjecture and sur-
mise than on that absolute logical proof which was so dear to
him. There is, however, one of these last which was so remark-
able in its details and so startling in its results that I am tempted
to give some account of it in spite of the fact that there are points

In [1]:
f=open("orange.txt","r")
data = f.readlines()
print(data)
f.close()

['                The Five Orange Pips\n', '\n', '  When I glance over my notes and records of the Sherlock\n', "Holmes cases between the years '82 and '90, I am faced by so\n", 'many which present strange and interesting features that it is no\n', 'easy matter to know which to choose and which to leave. Some,\n', 'however, have already gained publicity through the papers, and\n', 'others have not offered a field for those peculiar qualities which\n', 'my friend possessed in so high a degree, and which it is the\n', 'object of these papers to illustrate. Some, too, have baffled his\n', 'analytical skill, and would be, as narratives, beginnings without\n', 'an ending, while others have been but partially cleared up, and\n', 'have their explanations founded rather upon conjecture and sur-\n', 'mise than on that absolute logical proof which was so dear to\n', 'him. There is, however, one of these last which was so remark-\n', 'able in its details and so startling in its results that I am 

In [7]:
f=open("orange.txt","r")
data = f.read().splitlines()
print(data)
f.close()

['                The Five Orange Pips', '', '  When I glance over my notes and records of the Sherlock', "Holmes cases between the years '82 and '90, I am faced by so", 'many which present strange and interesting features that it is no', 'easy matter to know which to choose and which to leave. Some,', 'however, have already gained publicity through the papers, and', 'others have not offered a field for those peculiar qualities which', 'my friend possessed in so high a degree, and which it is the', 'object of these papers to illustrate. Some, too, have baffled his', 'analytical skill, and would be, as narratives, beginnings without', 'an ending, while others have been but partially cleared up, and', 'have their explanations founded rather upon conjecture and sur-', 'mise than on that absolute logical proof which was so dear to', 'him. There is, however, one of these last which was so remark-', 'able in its details and so startling in its results that I am tempted', 'to give some accoun

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(data)
print(response)

  (0, 992)	0.679640890684868
  (0, 932)	0.7335449950133116
  (2, 1240)	0.416186349030748
  (2, 1115)	0.46470592902508673
  (2, 906)	0.5526469589210581
  (2, 582)	0.5526469589210581
  (3, 483)	0.45294371475631556
  (3, 17)	0.45294371475631556
  (3, 12)	0.45294371475631556
  (3, 1575)	0.370754949665097
  (3, 199)	0.40746910205675246
  (3, 648)	0.284667651755769
  (4, 502)	0.511202263687555
  (4, 706)	0.5430978727321433
  (4, 1345)	0.47101854859152853
  (4, 1044)	0.47101854859152853
  (5, 760)	0.4278741815412604
  (5, 227)	0.5088451652116731
  (5, 735)	0.4278741815412604
  (5, 837)	0.4066711596644491
  (5, 410)	0.45775816243806106
  (6, 955)	0.4342439445950932
  (6, 1068)	0.6369584745422945
  (6, 568)	0.6369584745422945
  (7, 1078)	0.5
  :	:
  (725, 1192)	0.4618359403662025
  (725, 1322)	0.4358836098131304
  (725, 802)	0.4358836098131304
  (725, 897)	0.5012362652669419
  (725, 804)	0.3943104461713669
  (726, 631)	0.5518679133911024
  (726, 1097)	0.5518679133911024
  (726, 363)	0.402246276

In [10]:
vectorizer.get_feature_names()

['000',
 '10',
 '12th',
 '14',
 '1869',
 '1870',
 '1878',
 '1883',
 '1oth',
 '2d',
 '4th',
 '7th',
 '82',
 '83',
 '84',
 '85',
 '87',
 '90',
 '9th',
 'abjure',
 'able',
 'abound',
 'absence',
 'absolute',
 'abuse',
 'accident',
 'accidental',
 'accidents',
 'accomplishment',
 'account',
 'accurately',
 'accused',
 'act',
 'acted',
 'addressed',
 'ado',
 'advantages',
 'adventure',
 'adventures',
 'advice',
 'advise',
 'advised',
 'affair',
 'affairs',
 'afraid',
 'agitation',
 'ago',
 'ah',
 'aid',
 'air',
 'alarm',
 'albert',
 'allowed',
 'amateur',
 'america',
 'american',
 'americans',
 'amid',
 'analysis',
 'analytical',
 'anatomy',
 'anderson',
 'angry',
 'animal',
 'answer',
 'answered',
 'anxiety',
 'anxiously',
 'apology',
 'appeal',
 'appears',
 'argue',
 'arm',
 'armed',
 'arms',
 'army',
 'arrived',
 'art',
 'ary',
 'ascended',
 'ashes',
 'ask',
 'asked',
 'assert',
 'assume',
 'astronomy',
 'atlantic',
 'attain',
 'attention',
 'attic',
 'attics',
 'attracted',
 'augustine'

In [11]:
response.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])